// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    I18nSetting: typeof import('./components/Header/I18nSetting.vue')['default']
    ICifTw: typeof import('~icons/cif/tw')['default']
    ICifUs: typeof import('~icons/cif/us')['default']
    'IGameIcons:click': typeof import('~icons/game-icons/click')['default']
    'IIconamoon:closeBold': typeof import('~icons/iconamoon/close-bold')['default']
    'IIconamoon:menuBurgerHorizontalBold': typeof import('~icons/iconamoon/menu-burger-horizontal-bold')['default']
    IMdiLanguage: typeof import('~icons/mdi/language')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar/index.vue')['default']
  }
}
