// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutContent: typeof import('./components/AboutContent/index.vue')['default']
    CarouselPortfolio: typeof import('./components/PortfolioComponent/CarouselPortfolio.vue')['default']
    Description: typeof import('./components/AboutContent/Description.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    I18nSetting: typeof import('./components/Header/I18nSetting.vue')['default']
    ICifTw: typeof import('~icons/cif/tw')['default']
    ICifUs: typeof import('~icons/cif/us')['default']
    'IFluent:open12Filled': typeof import('~icons/fluent/open12-filled')['default']
    'IIconamoon:closeBold': typeof import('~icons/iconamoon/close-bold')['default']
    'IIconamoon:menuBurgerHorizontalBold': typeof import('~icons/iconamoon/menu-burger-horizontal-bold')['default']
    'IIconPark:left': typeof import('~icons/icon-park/left')['default']
    'IIconPark:right': typeof import('~icons/icon-park/right')['default']
    'IIconParkOutline:leftC': typeof import('~icons/icon-park/left-c')['default']
    'IIconParkSolid:leftC': typeof import('~icons/icon-park/left-c')['default']
    'IIconParkSolid:leftOne': typeof import('~icons/icon-park/left-one')['default']
    IMdiLanguage: typeof import('~icons/mdi/language')['default']
    'IZondicons:closeSolid': typeof import('~icons/zondicons/close-solid')['default']
    Open: typeof import('./components/PortfolioComponent/Open.vue')['default']
    PortfolioContent: typeof import('./components/PortfolioComponent/PortfolioContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar/index.vue')['default']
  }
}
